pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: armeabi_v7a
  displayName: 'armeabi-v7a'
  dependsOn: []
  steps:
  - template: azure-templates/bazel-install-steps.yml
  - script: |
      bazel build //... --config=armeabi-v7a
      file bazel-bin/hello | grep "ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV)"
    displayName: "Build"
  - script:
      ./scripts/armeabi-v7a-docker-test.sh
    displayName: "Test"
- job: armeabi_v6
  displayName: 'armeabi-v6'
  dependsOn: []
  steps:
  - template: azure-templates/bazel-install-steps.yml
  - script: |
      bazel build //... --config=armeabi-v6
      file bazel-bin/hello | grep "ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV)"
    displayName: "Build"
  - script:
      ./scripts/armeabi-v6-docker-test.sh
    displayName: "Test"
