trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    sudo apt-get install wget patch file
    wget https://github.com/bazelbuild/bazel/releases/download/1.0.1/bazel_1.0.1-linux-x86_64.deb -O bazel.deb
    sudo apt install ./bazel.deb
    bazel build //... --config=armeabi-v7a
    file bazel-bin/hello | grep "ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV)"
  displayName: 'Bazel build'
